// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn9REH2f9AGYpwrMHkS36omh35FwLsK2U',
    appId: '1:387077556716:web:62e35fd09b55080b6b98c9',
    messagingSenderId: '387077556716',
    projectId: 'efrei-todo2025',
    authDomain: 'efrei-todo2025.firebaseapp.com',
    storageBucket: 'efrei-todo2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ncnnH-MrzjAvsmIHATmKo103vEz-7ck',
    appId: '1:387077556716:android:9e7f631f53b250db6b98c9',
    messagingSenderId: '387077556716',
    projectId: 'efrei-todo2025',
    storageBucket: 'efrei-todo2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0SVIHDCPjH_ZbNeCGwp-yRM9dTGHbOvs',
    appId: '1:387077556716:ios:6233d3a9184714926b98c9',
    messagingSenderId: '387077556716',
    projectId: 'efrei-todo2025',
    storageBucket: 'efrei-todo2025.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0SVIHDCPjH_ZbNeCGwp-yRM9dTGHbOvs',
    appId: '1:387077556716:ios:6233d3a9184714926b98c9',
    messagingSenderId: '387077556716',
    projectId: 'efrei-todo2025',
    storageBucket: 'efrei-todo2025.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn9REH2f9AGYpwrMHkS36omh35FwLsK2U',
    appId: '1:387077556716:web:28a6fff002a5d03d6b98c9',
    messagingSenderId: '387077556716',
    projectId: 'efrei-todo2025',
    authDomain: 'efrei-todo2025.firebaseapp.com',
    storageBucket: 'efrei-todo2025.firebasestorage.app',
  );
}
